### ISSUE TITLE
Alert Developers!!! Admin module do not show consumer details. Please fix it Asap!

### ISSUE THREAD

**Issue by Rojan404** [rxmxndai/Water-Billing-System-HCK#4]
![issue12](https://user-images.githubusercontent.com/102160854/162750370-477984bd-c179-4480-b013-6189b926dbd1.png)

**Comment by Rojan404** [comment]
![Uploading issue12.png…]()

**Comment by rxmxndai** [comment]
I fixed the issue regarding consumer details page.

![image](https://user-images.githubusercontent.com/82092038/162749884-e1ba883b-0525-4dc1-85ea-8e57d3cddbd3.png)

**Comment by rxmann** [comment]
I fixed the issue regarding the consumer details page.
![image](https://user-images.githubusercontent.com/82092038/162750539-d1c38043-19bc-4fb0-965a-e0331ac91782.png)
