### ISSUE TITLE
While we are printing the pdf "White label error is being displayed in the description".

### ISSUE THREAD

**Issue by Rojan404** [rxmxndai/Water-Billing-System-HCK#6]

**Comment by rxmann** [comment]
Well, I guess, The error is due to bad handling of mapping request.
I shall give it a look. It might take some time. Please wait.

**Comment by rxmann** [comment]
Does any one know javaScript?

**Comment by rxmann** [comment]
We might make our webpage downloadable using javascript

**Comment by Rojan404** [comment]
I guess none

**Comment by rxmann** [comment]
I will give it a try.

**Comment by Rojan404** [comment]
Okay

**Comment by rxmann** [comment]
The bug is fixed. I used javaScript to download the webpage (Invoice)
![image](https://user-images.githubusercontent.com/82092038/167378638-7d54835b-2aaf-4651-a555-e83adda55341.png)

**Comment by rxmann** [comment]
The ibug is fixed now. please check again.
